# Generated by Django 6.0.2 on 2026-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('feature', models.CharField(max_length=100)),
                ('reference_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ats_score', models.IntegerField()),
                ('strengths', models.TextField()),
                ('suggestions', models.TextField()),
                ('missing_keywords', models.TextField()),
                ('detected_skills', models.TextField()),
                ('resume_pdf', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('target_role', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
